version: "3"

services:
  as:
    build: .
    environment:
      - MYSQL_URI=db:3306
    ports:
      - "8080:8080"
      - "9990:9990"

  db:
    image: "mysql:5.7"
    environment:
      - MYSQL_DATABASE=sample
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
      - MYSQL_ROOT_PASSWORD=supersecret
    volumes:
      - ./workdir/db/data/:/var/lib/mysql/              # data storage
    ports:
    - "3306:3306"
